### ISSUE TITLE
How to access quest cameras?

### ISSUE THREAD

**Issue by ablueatworld** [ZhengyiLuo/SimXR#1]
Hi,

Thank you so much for your work and for openly sharing it. I have gone through your outstanding publication and code to see how you are accessing the Quest's egocentric cameras. As far as I know, accessing the Quest's cameras is restricted by Meta for safety reasons. Could you please explain how you managed to obtain the camera data stream?

Thanks in advance.

**Comment by ZhengyiLuo** [comment]
Hi!

Thank you for your interest in our work! SimXR is a work done in collaboration with Meta Realty Labs so we have internal access to the camera data streams. All of the training data will be released; working on them now. Sorry for the delays!
